# Generated by Django 4.2.6 on 2023-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbackd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('num', models.IntegerField()),
                ('feed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname1', models.TextField()),
                ('email2', models.EmailField(max_length=254)),
                ('num1', models.IntegerField()),
                ('Time', models.CharField(max_length=20)),
            ],
        ),
    ]
